api_token_env: CROWDIN_PERSONAL_TOKEN
project_id_env: CROWDIN_PROJECT_ID
base_path: .
preserve_hierarchy: true

files:
  - source: basiliskLLM.pot
    translation: basilisk/res/locale/%locale_with_underscore%/LC_MESSAGES/basiliskLLM.po
    languages_mapping:
      locale_with_underscore:
        fr_FR: fr
        ru_RU: ru
        tr_TR: tr
        uk_UA: uk
